# -*- coding: utf-8 -*-
"""220901(1-1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1By9t_R05zqMvP8JLHWNhivhxnJFU1EtJ
"""

print('hello world')

'hello world'

